In [1]:
# %%
import pandas as pd
import numpy as np

from pathlib import Path
from scipy.stats import chi2_contingency

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)

In [2]:
# %%
PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data" / "model_matrix.parquet"

In [3]:
# %%
df = pd.read_parquet(DATA_PATH)

df.shape, df.columns.tolist()

((535391, 39),
 ['browser_desktop_web',
  'os_name_clean_Android',
  'os_name_clean_Chrome OS',
  'os_name_clean_Other',
  'os_name_clean_Windows',
  'os_name_clean_macOS',
  'sub_region_East North Central',
  'sub_region_East South Central',
  'sub_region_Middle Atlantic',
  'sub_region_Mountain',
  'sub_region_New England',
  'sub_region_Pacific',
  'sub_region_West North Central',
  'sub_region_West South Central',
  'test_engagement_state_Test Completed',
  'test_engagement_state_Test Started Only',
  'tests_taken_count_bucket_1',
  'tests_taken_count_bucket_2–3',
  'tests_taken_count_bucket_4+',
  'tests_completed_count_bucket_1',
  'tests_completed_count_bucket_2+',
  'first_test_domain_Addiction & Compulsive Behavior',
  'first_test_domain_Anxiety & Stress',
  'first_test_domain_Life, Work & Physical Health',
  'first_test_domain_Mood & Depression',
  'first_test_domain_Neurodevelopmental & Cognitive',
  'first_test_domain_Personality Disorders & Traits',
  'first_test_domain_Sexual & Gender Health',
  'first_test_domain_Trauma & Dissociation',
  'first_completed_test_domain_Addiction & Compulsive Behavior',
  'first_completed_test_domain_Anxiety & Stress',
  'first_completed_test_domain_Life, Work & Physical Health',
  'first_completed_test_domain_Mood & Depression',
  'first_completed_test_domain_Neurodevelopmental & Cognitive',
  'first_completed_test_domain_Personality Disorders & Traits',
  'first_completed_test_domain_Sexual & Gender Health',
  'first_completed_test_domain_Trauma & Dissociation',
  'has_signup',
  'visitor_key'])

In [4]:
# %%
assert "has_signup" in df.columns
assert df["has_signup"].dropna().isin([0, 1, True, False]).all()

In [5]:
# %%
TARGET = "has_signup"
ID_COLS = ["visitor_key"]

FEATURE_COLS = [
    c for c in df.columns
    if c not in ID_COLS + [TARGET]
]

len(FEATURE_COLS)

37

In [6]:
# %%
non_binary = [
    c for c in FEATURE_COLS
    if not set(df[c].dropna().unique()).issubset({0, 1})
]

non_binary

[]

In [7]:
# %%
def chi_square_binary_feature(df, feature, target="has_signup"):
    """
    Runs a Chi-square test between a binary feature and binary target.
    Returns stats + interpretable metrics.
    """
    contingency = pd.crosstab(df[feature], df[target])

    # Ensure full 2x2 table
    if contingency.shape != (2, 2):
        return None

    chi2, p_value, _, _ = chi2_contingency(contingency)

    signup_rate_when_present = (
        contingency.loc[1, 1] / contingency.loc[1].sum()
        if 1 in contingency.index else np.nan
    )

    support = contingency.loc[1].sum() if 1 in contingency.index else 0

    return {
        "feature": feature,
        "chi2": chi2,
        "p_value": p_value,
        "signup_rate_when_present": signup_rate_when_present,
        "support": support
    }

In [8]:
# %%
results = []

for feature in FEATURE_COLS:
    res = chi_square_binary_feature(df, feature, TARGET)
    if res:
        results.append(res)

results_df = pd.DataFrame(results)
results_df.shape

(37, 5)

In [9]:
# %%
results_df = results_df.sort_values("p_value")
results_df.head(20)

,feature,chi2,p_value,signup_rate_when_present,support
14,test_engagement_state_Test Completed,2080.925450,0.000000e+00,0.020321,425185
19,tests_completed_count_bucket_1,2583.690581,0.000000e+00,0.022265,366807
15,test_engagement_state_Test Started Only,1410.245778,1.247399e-308,0.000503,77550
32,first_completed_test_domain_Mood & Depression,857.037037,2.146382e-188,0.027191,95326
16,tests_taken_count_bucket_1,667.350452,3.765349e-147,0.018884,401457
24,first_test_domain_Mood & Depression,498.028958,2.551707e-110,0.023934,109218
0,browser_desktop_web,295.630741,2.949230e-66,0.009311,82269
20,tests_completed_count_bucket_2+,274.048621,1.487832e-61,0.008102,58378
18,tests_taken_count_bucket_4+,223.219167,1.795658e-50,0.006562,35354
1,os_name_clean_Android,132.183210,1.364291e-30,0.019533,147286
36,first_completed_test_domain_Trauma & Dissociation,79.894916,3.948612e-19,0.019844,85920
7,sub_region_East South Central,65.132553,7.002569e-16,0.021397,37575
3,os_name_clean_Other,57.800766,2.900568e-14,0.004830,7039
4,os_name_clean_Windows,56.364897,6.019547e-14,0.011061,31192
17,tests_taken_count_bucket_2–3,46.710368,8.229245e-12,0.013136,65924
25,first_test_domain_Neurodevelopmental & Cognitive,36.236216,1.747919e-09,0.008907,10554
11,sub_region_Pacific,36.063358,1.910049e-09,0.013712,74678
5,os_name_clean_macOS,35.313884,2.806244e-09,0.010026,14163
13,sub_region_West South Central,33.482344,7.191386e-09,0.018957,66942
35,first_completed_test_domain_Sexual & Gender He...,29.173833,6.616679e-08,0.019197,50788

In [10]:
# %%
results_df["significant_0_05"] = results_df["p_value"] < 0.05
results_df["significant_0_01"] = results_df["p_value"] < 0.01

results_df["significant_0_05"].value_counts()

significant_0_05
True     28
False     9
Name: count, dtype: int64

In [13]:
# %%
MIN_SUPPORT = 500  # adjust as needed

filtered = results_df[
    (results_df["support"] >= MIN_SUPPORT) &
    (results_df["p_value"] < 0.05)
]

filtered

,feature,chi2,p_value,signup_rate_when_present,support,significant_0_05,significant_0_01
14,test_engagement_state_Test Completed,2080.925450,0.000000e+00,0.020321,425185,True,True
19,tests_completed_count_bucket_1,2583.690581,0.000000e+00,0.022265,366807,True,True
15,test_engagement_state_Test Started Only,1410.245778,1.247399e-308,0.000503,77550,True,True
32,first_completed_test_domain_Mood & Depression,857.037037,2.146382e-188,0.027191,95326,True,True
16,tests_taken_count_bucket_1,667.350452,3.765349e-147,0.018884,401457,True,True
24,first_test_domain_Mood & Depression,498.028958,2.551707e-110,0.023934,109218,True,True
0,browser_desktop_web,295.630741,2.949230e-66,0.009311,82269,True,True
20,tests_completed_count_bucket_2+,274.048621,1.487832e-61,0.008102,58378,True,True
18,tests_taken_count_bucket_4+,223.219167,1.795658e-50,0.006562,35354,True,True
1,os_name_clean_Android,132.183210,1.364291e-30,0.019533,147286,True,True
36,first_completed_test_domain_Trauma & Dissociation,79.894916,3.948612e-19,0.019844,85920,True,True
7,sub_region_East South Central,65.132553,7.002569e-16,0.021397,37575,True,True
3,os_name_clean_Other,57.800766,2.900568e-14,0.004830,7039,True,True
4,os_name_clean_Windows,56.364897,6.019547e-14,0.011061,31192,True,True
17,tests_taken_count_bucket_2–3,46.710368,8.229245e-12,0.013136,65924,True,True
25,first_test_domain_Neurodevelopmental & Cognitive,36.236216,1.747919e-09,0.008907,10554,True,True
11,sub_region_Pacific,36.063358,1.910049e-09,0.013712,74678,True,True
5,os_name_clean_macOS,35.313884,2.806244e-09,0.010026,14163,True,True
13,sub_region_West South Central,33.482344,7.191386e-09,0.018957,66942,True,True
35,first_completed_test_domain_Sexual & Gender He...,29.173833,6.616679e-08,0.019197,50788,True,True
31,"first_completed_test_domain_Life, Work & Physi...",25.019021,5.676753e-07,0.021101,17061,True,True
22,first_test_domain_Anxiety & Stress,20.568230,5.754317e-06,0.013101,30685,True,True
33,first_completed_test_domain_Neurodevelopmental...,19.572474,9.685464e-06,0.010475,9260,True,True
9,sub_region_Mountain,15.955069,6.486386e-05,0.013958,43274,True,True
34,first_completed_test_domain_Personality Disord...,15.720792,7.341276e-05,0.017785,94741,True,True
10,sub_region_New England,14.801880,1.194164e-04,0.012966,20823,True,True
21,first_test_domain_Addiction & Compulsive Behavior,11.116227,8.557569e-04,0.014613,56593,True,True
2,os_name_clean_Chrome OS,8.489539,3.571944e-03,0.020868,6661,True,True

In [12]:
# %%
filtered.assign(
    feature_group=filtered["feature"].str.split("_").str[0]
).groupby("feature_group").size().sort_values(ascending=False)

feature_group
first      10
os          5
tests       5
sub         5
test        2
browser     1
dtype: int64